/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class now_lib_jni_NowJNICaller */

#ifndef _Included_now_lib_jni_NowJNICaller
#define _Included_now_lib_jni_NowJNICaller
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     now_lib_jni_NowJNICaller
 * Method:    getControlSignatureUnderMouse
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_now_lib_jni_NowJNICaller_getControlSignatureUnderMouse
  (JNIEnv *, jobject);

/*
 * Class:     now_lib_jni_NowJNICaller
 * Method:    getUIInformation
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_now_lib_jni_NowJNICaller_getUIInformation
  (JNIEnv *, jobject, jstring);

/*
 * Class:     now_lib_jni_NowJNICaller
 * Method:    getControlProperty
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_now_lib_jni_NowJNICaller_getControlProperty
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
