/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class now_lib_jni_NowJNICaller */

#ifndef _Included_now_lib_jni_NowJNICaller
#define _Included_now_lib_jni_NowJNICaller
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     now_lib_jni_NowJNICaller
 * Method:    getHelpText
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_now_lib_jni_NowJNICaller_getHelpText
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
