/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class now_jni_caller_NowJNICaller */

#ifndef _Included_now_jni_caller_NowJNICaller
#define _Included_now_jni_caller_NowJNICaller
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     now_jni_caller_NowJNICaller
 * Method:    displayMessage
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_now_jni_caller_NowJNICaller_displayMessage
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
